In [42]:
import pandas as pd
import matplotlib.pyplot as plt

ride_data = pd.read_csv("raw_data/ride_data.csv")
city_data = pd.read_csv("raw_data/ride_data.csv")

ride_df = pd.DataFrame({
    "Average Fare ($) Per City": ride_data.groupby(["city"]).mean()["fare"].map("${:,.2f}".format),
    "Total Number of Rides Per City": ride_data.groupby(["city"]).count()["ride_id"]
})

ride_df_reset = ride_data.reset_index()
city_df_reset = city_data.reset_index()

ride_df_reset

      index                  city                 date   fare        ride_id
0         0              Sarabury  2016-01-16 13:49:27  38.35  5403689035038
1         1             South Roy  2016-01-02 18:42:34  17.49  4036272335942
2         2           Wiseborough  2016-01-21 17:35:29  44.18  3645042422587
3         3           Spencertown  2016-07-31 14:53:22   6.87  2242596575892
4         4            Nguyenbury  2016-07-09 04:42:44   6.28  1543057793673
5         5           New Jeffrey  2016-02-22 18:36:25  36.01  9757888452346
6         6         Port Johnstad  2016-06-07 02:39:58  17.15  4352278259335
7         7             Jacobfort  2016-09-20 20:58:37  22.98  1500221409082
8         8           Travisville  2016-01-15 17:32:02  27.39   850152768361
9         9            Sandymouth  2016-11-16 07:27:00  21.61  2389035050524
10       10       New Andreamouth  2016-04-11 07:20:48   7.72  9992929847990
11       11         New Christine  2016-09-13 15:06:42  24.89  7918411468537
12       12           Stewartview  2016-03-29 05:15:56  23.88  6778235889588
13       13        Rodriguezburgh  2016-09-05 05:20:39   4.54  9650770953139
14       14      West Sydneyhaven  2016-08-02 21:18:44  12.87  7994760397230
15       15           Swansonbury  2016-07-11 18:42:11  39.30   744481862626
16       16              Lisatown  2016-07-05 18:09:14   5.82  6370359473201
17       17             East Erin  2016-11-03 01:03:05   7.51  4744239092530
18       18       Port Martinberg  2016-01-06 17:11:30   8.66  7298562820881
19       19           Wiseborough  2016-09-12 18:43:41  26.83  9304728540000
20       20           Edwardsbury  2016-02-27 03:55:54  20.17  8514523868075
21       21             Jacobfort  2016-06-12 17:01:29  34.47  4135673527977
22       22           Pamelahaven  2016-03-26 12:56:57  36.43  3015329826849
23       23            Fosterside  2016-08-12 11:52:41  28.08   133077693483
24       24             Jacobfort  2016-09-17 12:38:58  38.25  2182376146051
25       25      West Sydneyhaven  2016-08-23 14:49:59  36.12  5885997568611
26       26           West Alexis  2016-01-16 00:33:02  26.62  1574788996743
27       27           Carrollfort  2016-06-24 20:11:11   6.45  1092683495142
28       28             New David  2016-01-12 20:48:43  38.68  5229089333754
29       29           Stewartview  2016-10-15 05:26:40  11.74  8402784599831
...     ...                   ...                  ...    ...            ...
2345   2345        West Kevintown  2016-06-15 19:53:16  13.50  9577921579881
2346   2346           Matthewside  2016-02-23 00:43:51  40.84  8665248512368
2347   2347              Erikport  2016-11-26 04:39:52  44.21  9598643212986
2348   2348             Kinghaven  2016-07-23 08:23:50  46.08  8440329717166
2349   2349        Hernandezshire  2016-02-24 17:30:44  44.68  6389115653382
2350   2350          Kennethburgh  2016-01-01 04:31:43  33.53  5149088250183
2351   2351           Stevensport  2016-02-22 02:45:07  19.91   808097865942
2352   2352  South Elizabethmouth  2016-11-23 07:47:18  46.39  1939838068038
2353   2353          East Stephen  2016-07-30 21:25:01  35.39  1107870956099
2354   2354           Jacksonfort  2016-10-01 13:41:00  34.17  7750597960630
2355   2355          Kennethburgh  2016-04-30 20:44:27  23.58  4524301143267
2356   2356             Horneland  2016-03-25 02:05:42  20.04  5729327140644
2357   2357           Shelbyhaven  2016-01-25 01:39:16  59.43  8088329954312
2358   2358              Erikport  2016-08-03 21:19:11  47.67  9201708664049
2359   2359          Kennethburgh  2016-11-19 06:59:31  18.37  5897895798960
2360   2360           Jacksonfort  2016-10-20 16:42:54  37.75  4356781814784
2361   2361          South Joseph  2016-10-15 03:53:06  32.50  2758038144583
2362   2362           Matthewside  2016-05-18 02:00:30  48.67  2049161404256
2363   2363           Matthewside  2016-08-08 14:02:35  24.97  2872494724827
2364   2364          South Joseph  2016-10-28 09:52:15  25.34  6706101910500
2365   2365  South Elizabethmouth  2016-07-19 09:35:59  31.09  2959749591417
2366   2366         North Whitney  2016-11-11 16:24:16  22.99  3454326063039
2367   2367          New Johnbury  2016-08-29 02:36:06  18.83  7368222134792
2368   2368           East Leslie  2016-06-22 07:45:30  34.54   684950063164
2369   2369          Kennethburgh  2016-06-07 11:43:43  56.02   311733202150
2370   2370        West Kevintown  2016-02-10 00:50:04  34.69  9595491362610
2371   2371         East Troybury  2016-03-14 01:55:32  38.80  9205811495606
2372   2372         North Whitney  2016-01-26 01:06:41  34.92  4165974278063
2373   2373          South Joseph  2016-09-28 07:30:55  12.55  4336212615821
2374   2374  South Elizabethmouth  2016-04-21 10:20:09  16.50  5702608059064

[2375 rows x 5 columns]

In [34]:
city_data

                      city                 date   fare        ride_id
0                 Sarabury  2016-01-16 13:49:27  38.35  5403689035038
1                South Roy  2016-01-02 18:42:34  17.49  4036272335942
2              Wiseborough  2016-01-21 17:35:29  44.18  3645042422587
3              Spencertown  2016-07-31 14:53:22   6.87  2242596575892
4               Nguyenbury  2016-07-09 04:42:44   6.28  1543057793673
5              New Jeffrey  2016-02-22 18:36:25  36.01  9757888452346
6            Port Johnstad  2016-06-07 02:39:58  17.15  4352278259335
7                Jacobfort  2016-09-20 20:58:37  22.98  1500221409082
8              Travisville  2016-01-15 17:32:02  27.39   850152768361
9               Sandymouth  2016-11-16 07:27:00  21.61  2389035050524
10         New Andreamouth  2016-04-11 07:20:48   7.72  9992929847990
11           New Christine  2016-09-13 15:06:42  24.89  7918411468537
12             Stewartview  2016-03-29 05:15:56  23.88  6778235889588
13          Rodriguezburgh  2016-09-05 05:20:39   4.54  9650770953139
14        West Sydneyhaven  2016-08-02 21:18:44  12.87  7994760397230
15             Swansonbury  2016-07-11 18:42:11  39.30   744481862626
16                Lisatown  2016-07-05 18:09:14   5.82  6370359473201
17               East Erin  2016-11-03 01:03:05   7.51  4744239092530
18         Port Martinberg  2016-01-06 17:11:30   8.66  7298562820881
19             Wiseborough  2016-09-12 18:43:41  26.83  9304728540000
20             Edwardsbury  2016-02-27 03:55:54  20.17  8514523868075
21               Jacobfort  2016-06-12 17:01:29  34.47  4135673527977
22             Pamelahaven  2016-03-26 12:56:57  36.43  3015329826849
23              Fosterside  2016-08-12 11:52:41  28.08   133077693483
24               Jacobfort  2016-09-17 12:38:58  38.25  2182376146051
25        West Sydneyhaven  2016-08-23 14:49:59  36.12  5885997568611
26             West Alexis  2016-01-16 00:33:02  26.62  1574788996743
27             Carrollfort  2016-06-24 20:11:11   6.45  1092683495142
28               New David  2016-01-12 20:48:43  38.68  5229089333754
29             Stewartview  2016-10-15 05:26:40  11.74  8402784599831
...                    ...                  ...    ...            ...
2345        West Kevintown  2016-06-15 19:53:16  13.50  9577921579881
2346           Matthewside  2016-02-23 00:43:51  40.84  8665248512368
2347              Erikport  2016-11-26 04:39:52  44.21  9598643212986
2348             Kinghaven  2016-07-23 08:23:50  46.08  8440329717166
2349        Hernandezshire  2016-02-24 17:30:44  44.68  6389115653382
2350          Kennethburgh  2016-01-01 04:31:43  33.53  5149088250183
2351           Stevensport  2016-02-22 02:45:07  19.91   808097865942
2352  South Elizabethmouth  2016-11-23 07:47:18  46.39  1939838068038
2353          East Stephen  2016-07-30 21:25:01  35.39  1107870956099
2354           Jacksonfort  2016-10-01 13:41:00  34.17  7750597960630
2355          Kennethburgh  2016-04-30 20:44:27  23.58  4524301143267
2356             Horneland  2016-03-25 02:05:42  20.04  5729327140644
2357           Shelbyhaven  2016-01-25 01:39:16  59.43  8088329954312
2358              Erikport  2016-08-03 21:19:11  47.67  9201708664049
2359          Kennethburgh  2016-11-19 06:59:31  18.37  5897895798960
2360           Jacksonfort  2016-10-20 16:42:54  37.75  4356781814784
2361          South Joseph  2016-10-15 03:53:06  32.50  2758038144583
2362           Matthewside  2016-05-18 02:00:30  48.67  2049161404256
2363           Matthewside  2016-08-08 14:02:35  24.97  2872494724827
2364          South Joseph  2016-10-28 09:52:15  25.34  6706101910500
2365  South Elizabethmouth  2016-07-19 09:35:59  31.09  2959749591417
2366         North Whitney  2016-11-11 16:24:16  22.99  3454326063039
2367          New Johnbury  2016-08-29 02:36:06  18.83  7368222134792
2368           East Leslie  2016-06-22 07:45:30  34.54   684950063164
2369          Kennethburgh  2016-06-07 11:43:43  56.02   311733202150
2370        West Kevintown  2016-02-10 00:50:04  34.69  9595491362610
2371         East Troybury  2016-03-14 01:55:32  38.80  9205811495606
2372         North Whitney  2016-01-26 01:06:41  34.92  4165974278063
2373          South Joseph  2016-09-28 07:30:55  12.55  4336212615821
2374  South Elizabethmouth  2016-04-21 10:20:09  16.50  5702608059064

[2375 rows x 4 columns]

In [43]:
merged_df = pd.merge(ride_df_reset,city_df_reset,on="city",how="inner")
merged_df

,index_x,city,date_x,fare_x,ride_id_x,index_y,date_y,fare_y,ride_id_y
0,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,0,2016-01-16 13:49:27,38.35,5403689035038
1,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,44,2016-07-23 07:42:44,21.76,7546681945283
2,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,62,2016-04-02 04:32:25,38.03,4932495851866
3,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,82,2016-06-23 05:03:41,26.82,6711035373406
4,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,127,2016-09-30 12:48:34,30.30,6388737278232
5,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,160,2016-08-04 00:25:52,27.20,2429366407526
6,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,216,2016-07-25 10:44:01,17.73,4467299640441
7,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,239,2016-06-22 16:24:01,23.94,6153395712431
8,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,265,2016-01-27 17:46:45,16.39,8220809448298
9,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,351,2016-04-26 11:31:30,21.80,5969441875705
10,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,472,2016-08-14 19:56:59,7.83,4979570237054
11,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,519,2016-01-06 03:02:55,5.19,9988466326333
12,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,542,2016-03-29 15:47:35,17.00,3574423871181
13,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,651,2016-11-20 11:44:23,28.47,3793266633941
14,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,717,2016-07-17 20:41:06,17.79,9661023488490
15,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,749,2016-11-06 02:23:59,19.48,7305651789766
16,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,786,2016-09-26 07:30:31,26.71,6310253827816
17,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,802,2016-06-04 20:50:52,14.19,8765571028809
18,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,909,2016-01-22 23:12:06,38.40,1176229756048
19,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,919,2016-03-29 19:07:55,20.56,7019491956393
20,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,1037,2016-10-18 04:33:23,37.50,1054393799736
21,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,1308,2016-09-30 20:41:18,44.32,2103508227691
22,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,1314,2016-07-30 10:37:38,25.99,5233926699781
23,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,1464,2016-04-01 07:15:24,6.94,1931215121299
24,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,1497,2016-11-23 03:08:59,37.17,9141412183460
25,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,1556,2016-10-23 02:40:28,17.23,1977978528067
26,0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,1614,2016-04-06 21:02:54,7.14,6096364843852
27,44,Sarabury,2016-07-23 07:42:44,21.76,7546681945283,0,2016-01-16 13:49:27,38.35,5403689035038
28,44,Sarabury,2016-07-23 07:42:44,21.76,7546681945283,44,2016-07-23 07:42:44,21.76,7546681945283
29,44,Sarabury,2016-07-23 07:42:44,21.76,7546681945283,62,2016-04-02 04:32:25,38.03,4932495851866
...,...,...,...,...,...,...,...,...,...
52639,2352,South Elizabethmouth,2016-11-23 07:47:18,46.39,1939838068038,2305,2016-03-11 12:27:01,26.72,4943246873754
52640,2352,South Elizabethmouth,2016-11-23 07:47:18,46.39,1939838068038,2352,2016-11-23 07:47:18,46.39,1939838068038
52641,2352,South Elizabethmouth,2016-11-23 07:47:18,46.39,1939838068038,2365,2016-07-19 09:35:59,31.09,2959749591417
52642,2352,South Elizabethmouth,2016-11-23 07:47:18,46.39,1939838068038,2374,2016-04-21 10:20:09,16.50,5702608059064
52643,2365,South Elizabethmouth,2016-07-19 09:35:59,31.09,2959749591417,2295,2016-04-03 11:13:07,22.79,8193837300497
52644,2365,South Elizabethmouth,2016-07-19 09:35:59,31.09,2959749591417,2305,2016-03-11 12:27:01,26.72,4943246873754
52645,2365,South Elizabethmouth,2016-07-19 09:35:59,31.09,2959749591417,2352,2016-11-23 07:47:18,46.39,1939838068038
52646,2365,South Elizabethmouth,2016-07-19 09:35:59,31.09,2959749591417,2365,2016-07-19 09:35:59,31.09,2959749591417
52647,2365,South Elizabethmouth,2016-07-19 09:35:59,31.09,2959749591417,2374,2016-04-21 10:20:09,16.50,5702608059064
52648,2374,South Elizabethmouth,2016-04-21 10:20:09,16.50,5702608059064,2295,2016-04-03 11:13:07,22.79,8193837300497
52649,2374,South Elizabethmouth,2016-04-21 10:20:09,16.50,5702608059064,2305,2016-03-11 12:27:01,26.72,4943246873754
52650,2374,South Elizabethmouth,2016-04-21 10:20:09,16.50,5702608059064,2352,2016-11-23 07:47:18,46.39,1939838068038
52651,2374,South Elizabethmouth,2016-04-21 10:20:09,16.50,5702608059064,2365,2016-07-19 09:35:59,31.09,2959749591417
52652,2374,South Elizabethmouth,2016-04-21 10:20:09,16.50,5702608059064,2374,2016-04-21 10:20:09,16.50,5702608059064
52653,2324,Matthewside,2016-02-23 17:46:29,59.65,241191157535,2324,2016-02-23 17:46:29,59.65,241191157535
52654,2324,Matthewside,2016-02-23 17:46:29,59.65,241191157535,2346,2016-02-23 00:43:51,40.84,8665248512368
52655,2324,Matthewside,2016-02-23 17:46:29,59.65,241191157535,2362,2016-05-18 02:00:30,48.67,2049161404256
52656,2324,Matthewside,2016-02-23 17:46:29,59.65,241191157535,2363,2016-08-08 14:02:35,24.97,2872494724827
52657,2346,Matthewside,2016-02-23 00:43:51,40.84,8665248512368,2324,2016-02-23 17:46:29,59.65,241191157535
52658,2346,Matthewside,2016-02-23 00:43:51,40.84,8665248512368,2346,2016-02-23 00:43:51,40.84,8665248512368
52659,2346,Matthewside,2016-02-23 00:43:51,40.84,8665248512368,2362,2016-05-18 02:00:30,48.67,2049161404256
52660,2346,Matthewside,2016-02-23 00:43:51,40.84,8665248512368,2363,2016-08-08 14:02:35,24.97,2872494724827
52661,2362,Matthewside,2016-05-18 02:00:30,48.67,2049161404256,2324,2016-02-23 17:46:29,59.65,241191157535
52662,2362,Matthewside,2016-05-18 02:00:30,48.67,2049161404256,2346,2016-02-23 00:43:51,40.84,8665248512368
52663,2362,Matthewside,2016-05-18 02:00:30,48.67,2049161404256,2362,2016-05-18 02:00:30,48.67,2049161404256
52664,2362,Matthewside,2016-05-18 02:00:30,48.67,2049161404256,2363,2016-08-08 14:02:35,24.97,2872494724827
52665,2363,Matthewside,2016-08-08 14:02:35,24.97,2872494724827,2324,2016-02-23 17:46:29,59.65,241191157535
52666,2363,Matthewside,2016-08-08 14:02:35,24.97,2872494724827,2346,2016-02-23 00:43:51,40.84,8665248512368
52667,2363,Matthewside,2016-08-08 14:02:35,24.97,2872494724827,2362,2016-05-18 02:00:30,48.67,2049161404256
52668,2363,Matthewside,2016-08-08 14:02:35,24.97,2872494724827,2363,2016-08-08 14:02:35,24.97,2872494724827